# Generated by Django 4.2.9 on 2026-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_shape',
            field=models.CharField(choices=[('squircle', 'Squircle'), ('circle', 'Circle'), ('heart', 'Heart'), ('star', 'Star'), ('diamond', 'Diamond'), ('hexagon', 'Hexagon'), ('shield', 'Shield'), ('clover', 'Clover'), ('octagon', 'Octagon'), ('badge', 'Badge')], default='squircle', help_text='User avatar shape', max_length=32),
        ),
    ]
