# Generated by Django 5.2 on 2025-09-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_rename_banned_game_bandecision_game"),
        ("season", "0003_alter_season_status"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("otp", models.TextField()),
                ("failed_attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name="YearlyGameSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("selection_count", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
                (
                    "player_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_selections",
                        to="user.playerprofile",
                    ),
                ),
                (
                    "selected_in_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="season.season",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "selected_in_season"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player_profile", "year", "game", "selection_count"),
                        name="uniq_profile_year_game_selcount",
                    )
                ],
            },
        ),
    ]
