# Generated by Django 5.2 on 2025-09-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userinvitation_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="platformplayer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="platformplayer",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_links",
                to="user.platform",
            ),
        ),
        migrations.AlterField(
            model_name="platformplayer",
            name="player_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform_links",
                to="user.playerprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformplayer",
            constraint=models.UniqueConstraint(
                fields=("player_profile", "platform"), name="uniq_profile_platform"
            ),
        ),
    ]
