# Generated by Django 5.0.4 on 2024-06-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bga_name",
        ),
    ]
