# Generated by Django 5.2.8 on 2025-12-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvitelink',
            name='key_hash',
        ),
        migrations.AddField(
            model_name='userinvitelink',
            name='key',
            field=models.CharField(db_index=True, default='test', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
