# Generated by Django 4.2.9 on 2026-09-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(blank=True, default='', help_text='User avatar color hex or preset', max_length=32),
        ),
    ]
