# Generated by Django 5.2.8 on 2025-12-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userinvitelink_key_hash_userinvitelink_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvitelink',
            name='label',
            field=models.CharField(blank=True, help_text='Admin note to remember who this invite is for.', max_length=300),
        ),
    ]
