# Generated by Django 4.2.9 on 2026-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_shape',
            field=models.CharField(choices=[('squircle', 'Squircle'), ('circle', 'Circle'), ('heart', 'Heart'), ('star', 'Star'), ('hexagon', 'Hexagon'), ('shield', 'Shield'), ('clover', 'Clover'), ('meeple', 'Meeple'), ('beetle', 'Beetle'), ('fish', 'Fish'), ('snake', 'Snake'), ('crown', 'Crown'), ('cat', 'Cat')], default='squircle', help_text='User avatar shape', max_length=32),
        ),
    ]
