# Generated by Django 5.2.8 on 2025-12-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinvitelink_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitelink',
            name='player_profile',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this invite to an existing PlayerProfile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='user.playerprofile'),
        ),
    ]
