# Generated by Django 4.2.9 on 2026-09-24 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_avatar_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitelink',
            name='type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('password', 'Password')], default='invitation', help_text='Type of link: invitation or password reset.', max_length=32),
        ),
        migrations.AddField(
            model_name='userinvitelink',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Target user for password reset links.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinvitelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinvitelink',
            name='label',
            field=models.CharField(blank=True, help_text='Admin note to remember who this invite or reset is for.', max_length=300),
        ),
    ]
