# Generated by Django 4.2.9 on 2026-09-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userinvitelink_type_userinvitelink_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='elo_rating',
            field=models.FloatField(default=1500.0),
        ),
    ]
