"""
Django settings for django_rest project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present
load_dotenv(BASE_DIR / ".env")

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-3=2$mgwx0)o1(d*%5!92x-oaa(+7c1%1=n!3plo2pg_$q7z)dd"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",") if os.getenv("ALLOWED_HOSTS") else ["*"]
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

# Application definition

# Django apps
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "nested_admin",
    "django_filters",
    "django_extensions",
    "drf_spectacular",
    "drf_spectacular_sidecar",  # required for Swagger UI/Redoc
]

MY_APPS = [
    "game",
    "chat",
    "league",
    "season",
    "announcement",
    "release_note",
    "result",
    "user",
    "taskboard",
    "statistic",
    "configuration",
    "api",
    "notification",
]

INSTALLED_APPS = DJANGO_APPS + MY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
]
if "whitenoise" in [p.lower() for p in (DJANGO_APPS + MY_APPS)] or True:
    try:
        import whitenoise  # noqa: F401
        MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")
    except ImportError:
        pass

MIDDLEWARE.extend([
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
])

ROOT_URLCONF = "django_rest.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "dist/spa")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Kennerliga API",
    "DESCRIPTION": "API documentation kennerliga",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

WSGI_APPLICATION = "django_rest.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
if os.getenv("DATABASE_URL") and dj_database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    p for p in [
        os.path.join(BASE_DIR, "dist/spa"),
        os.path.join(BASE_DIR, "dist/spa/assets"),
        os.path.join(BASE_DIR, "dist/spa/icons"),
    ] if os.path.exists(p)
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "user.User"

ORIGIN_LIST = [
    "http://localhost:9000",
    "http://127.0.0.1:9000",
    "https://haligh.pythonanywhere.com",
    "http://haligh.pythonanywhere.com",
    "http://www.kennerliga.de",
    "https://www.kennerliga.de",
    "https://kennerliga.de",
]

# Add FRONTEND_URL or extra CORS origins from environment
_frontend_url = os.getenv("FRONTEND_URL")
if _frontend_url:
    for url in _frontend_url.split(","):
        cleaned = url.strip().rstrip("/")
        if cleaned and cleaned not in ORIGIN_LIST:
            ORIGIN_LIST.append(cleaned)

_cors_origins = os.getenv("CORS_ALLOWED_ORIGINS")
if _cors_origins:
    for url in _cors_origins.split(","):
        cleaned = url.strip().rstrip("/")
        if cleaned and cleaned not in ORIGIN_LIST:
            ORIGIN_LIST.append(cleaned)

CSRF_TRUSTED_ORIGINS = ORIGIN_LIST
CORS_ALLOWED_ORIGINS = ORIGIN_LIST

CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"

FRONTEND_REGISTER_URL = os.getenv(
    "FRONTEND_REGISTER_URL",
    f"{_frontend_url}/#/register" if _frontend_url else "http://localhost:9000/#/register",
)

DATA_UPLOAD_MAX_NUMBER_FIELDS = 4000

VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY")
VAPID_SUBJECT = os.getenv("VAPID_SUBJECT")
