# Generated by Django 4.2.9 on 2025-12-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
