# Generated by Django 5.2.4 on 2025-09-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='1 for L1, 2 for L2 etc.')),
                ('status', models.CharField(choices=[('PICKING', 'Picking'), ('BANNING', 'Banning'), ('REPICKING', 'Repicking'), ('PLAYING', 'Playing'), ('DONE', 'Done')], default='PICKING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_points', models.FloatField()),
                ('position', models.IntegerField()),
                ('last', models.BooleanField()),
            ],
        ),
    ]
