# Generated by Django 5.0.4 on 2024-06-09 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("league", "0001_initial"),
        ("season", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="members",
            field=models.ManyToManyField(
                related_name="leagues_member", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="season.season",
            ),
        ),
    ]
