# Generated by Django 5.0.3 on 2024-03-29 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('league', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='number',
            new_name='level',
        ),
    ]
