# Generated by Django 5.1.7 on 2025-03-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_initial'),
        ('season', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('Spielwahl', 'Picking'), ('Bannen', 'Banning'), ('Spielen', 'Playing'), ('Beendet', 'Done')], default='Spielwahl', max_length=20),
        ),
        migrations.AlterField(
            model_name='league',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='season.season'),
        ),
    ]
