# Generated by Django 4.2.9 on 2025-12-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_league_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamestanding',
            name='league_game_league__9b635e_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaguestanding',
            name='league_leag_league__cc32b5_idx',
        ),
        migrations.RemoveField(
            model_name='gamestanding',
            name='points',
        ),
        migrations.RemoveField(
            model_name='leaguestanding',
            name='points',
        ),
        migrations.AddIndex(
            model_name='gamestanding',
            index=models.Index(fields=['league', '-league_points'], name='league_game_league__63c48e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaguestanding',
            index=models.Index(fields=['league', '-league_points', '-wins'], name='league_leag_league__71692a_idx'),
        ),
    ]
