# Generated by Django 5.2 on 2025-10-10 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_selectedgame_unique_game_per_league"),
        ("league", "0003_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "league_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "win_share",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_standings",
                        to="league.league",
                    ),
                ),
                (
                    "player_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.playerprofile",
                    ),
                ),
                (
                    "selected_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="game.selectedgame",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["league", "selected_game"],
                        name="league_game_league__d50b22_idx",
                    ),
                    models.Index(
                        fields=["league", "-league_points", "-points"],
                        name="league_game_league__9b635e_idx",
                    ),
                ],
                "unique_together": {("selected_game", "player_profile")},
            },
        ),
        migrations.CreateModel(
            name="LeagueStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "wins",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "league_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="league.league",
                    ),
                ),
                (
                    "player_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.playerprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["league", "-league_points", "-wins", "-points"],
                        name="league_leag_league__cc32b5_idx",
                    )
                ],
                "unique_together": {("league", "player_profile")},
            },
        ),
    ]
