# Generated by Django 5.1.1 on 2024-10-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_league_active_player'),
        ('user', '0002_rename_player_platformplayer_player_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_points', models.FloatField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.playerprofile')),
            ],
        ),
    ]
