# Generated by Django 5.1.7 on 2025-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_league_status_alter_league_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('PICKING', 'Picking'), ('BANNING', 'Banning'), ('PLAYING', 'Playing'), ('DONE', 'Done')], default='PICKING', max_length=20),
        ),
    ]
