# Generated by Django 4.2.9 on 2026-01-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_gamestanding_decisive_tie_breaker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueResult',
        ),
    ]
