# Generated by Django 5.2 on 2025-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_league_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('PICKING', 'Picking'), ('BANNING', 'Banning'), ('REPICKING', 'Repicking'), ('PLAYING', 'Playing'), ('DONE', 'Done')], default='PICKING', max_length=20),
        ),
    ]
