# Generated by Django 5.1.4 on 2024-12-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_alter_league_season'),
        ('season', '0005_alter_seasonparticipant_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='active_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.seasonparticipant'),
        ),
        migrations.AlterField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(related_name='leagues_member', to='season.seasonparticipant'),
        ),
    ]
