# Generated by Django 4.1.2 on 2022-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='number',
            field=models.IntegerField(verbose_name='1 for the top league L1, 2 for L2 etc.'),
        ),
    ]
