# Generated by Django 5.0.4 on 2024-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('WINNER', 'Winner'), ('REGISTER', 'Register'), ('WARNING', 'Warning'), ('NEUTRAL', 'Neutral')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=88)),
                ('content', models.TextField(blank=True, null=True)),
                ('visible_until', models.DateTimeField()),
                ('visible_from', models.DateTimeField()),
            ],
        ),
    ]
