# Generated by Django 5.0.2 on 2024-03-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameoption',
            old_name='value',
            new_name='enabled',
        ),
    ]
