# Generated by Django 5.2.4 on 2025-09-28 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandecision',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_decisions', to='league.league'),
        ),
    ]
