# Generated by Django 5.1.7 on 2025-03-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        ('league', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_selections', to='game.game'),
        ),
        migrations.AlterField(
            model_name='selectedgame',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_selections', to='league.league'),
        ),
    ]
