# Generated by Django 5.1.7 on 2025-04-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_selectedgame_game_alter_selectedgame_league'),
        ('league', '0004_league_status_alter_league_season'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('name', 'platform'), name='unique_game_per_platform'),
        ),
        migrations.AddField(
            model_name='bandecision',
            name='banned_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.selectedgame'),
        ),
        migrations.AddField(
            model_name='bandecision',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_decisions', to='league.league'),
        ),
        migrations.AddField(
            model_name='bandecision',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_decisions', to='user.playerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='bandecision',
            unique_together={('league', 'player')},
        ),
    ]
