# Generated by Django 5.2.4 on 2025-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_initial'),
        ('league', '0003_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='selectedgame',
            constraint=models.UniqueConstraint(fields=('league', 'game'), name='unique_game_per_league'),
        ),
    ]
