# Generated by Django 5.2.8 on 2025-12-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=33),
        ),
    ]
