# Generated by Django 5.0.2 on 2024-03-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_is_active_gameoption_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameoption',
            old_name='value',
            new_name='is_activated',
        ),
        migrations.RenameField(
            model_name='gameoptionchoice',
            old_name='is_active',
            new_name='is_selected',
        ),
        migrations.AddField(
            model_name='gameoption',
            name='has_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameoption',
            name='only_if_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='only_if_options', to='game.gameoptionchoice'),
        ),
        migrations.AddField(
            model_name='gameoption',
            name='only_if_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='only_if_options', to='game.gameoption'),
        ),
        migrations.AddField(
            model_name='gameoption',
            name='only_if_value',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
