# Generated by Django 5.2.8 on 2025-12-17 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOptionAvailabilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_groups', to='game.gameoption')),
            ],
        ),
        migrations.CreateModel(
            name='GameOptionAvailabilityCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_value', models.BooleanField(blank=True, null=True)),
                ('negate', models.BooleanField(default=False, help_text='If true, invert the condition (NOT).')),
                ('depends_on_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_conditions', to='game.gameoption')),
                ('expected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by_conditions', to='game.gameoptionchoice')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='game.gameoptionavailabilitygroup')),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(
                        name='availability_condition_exactly_one_expected',
                        check=models.Q(
                            models.Q(('expected_value__isnull', False), ('expected_choice__isnull', True)),
                            models.Q(('expected_value__isnull', True), ('expected_choice__isnull', False)),
                            _connector='OR',
                        ),
                    )
                ],
            },
        ),
    ]