# Generated by Django 5.2 on 2025-05-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_bandecision_game_unique_game_per_platform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandecision',
            old_name='game',
            new_name='banned_game',
        ),
    ]
