# Generated by Django 5.2.8 on 2025-11-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_selectedgame_unique_game_per_league'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedgame',
            old_name='player',
            new_name='profile',
        ),
    ]
