# Generated by Django 5.2.8 on 2025-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameoptionavailabilitygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiebreaker',
            name='higher_wins',
            field=models.BooleanField(default=True, help_text='If True, higher values win. If False, lower values win.'),
        ),
    ]
