# Generated by Django 5.2.8 on 2025-12-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_player_selectedgame_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandecision',
            name='skipped_ban',
            field=models.BooleanField(default=False),
        ),
    ]
