# Generated by Django 5.0.3 on 2024-03-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_value_gameoption_is_activated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=88),
        ),
    ]
