# Generated by Django 5.2 on 2025-09-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_rename_banned_game_bandecision_game"),
        ("league", "0006_alter_league_status"),
        ("user", "0003_alter_platformplayer_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bandecision",
            old_name="player",
            new_name="player_banning",
        ),
        migrations.RenameField(
            model_name="bandecision",
            old_name="game",
            new_name="selected_game",
        ),
        migrations.AlterUniqueTogether(
            name="bandecision",
            unique_together={("league", "player_banning")},
        ),
    ]
