# Generated by Django 4.2.9 on 2025-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_tiebreaker_higher_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiebreaker',
            name='order',
            field=models.PositiveIntegerField(help_text='Higher order is more important.'),
        ),
    ]
