# Generated by Django 5.0.3 on 2024-03-29 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0006_alter_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameoption',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='gameoptionchoice',
            name='is_selected',
        ),
    ]
