# Generated by Django 4.2.9 on 2025-12-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_faction_options_faction_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameoption',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='gameoptionchoice',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='gameoption',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameoptionchoice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
