# Generated by Django 4.2.9 on 2025-12-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gameoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiebreaker',
            options={'ordering': ['-order']},
        ),
    ]
