# Generated by Django 4.2.9 on 2025-12-28 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_tiebreaker_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedgame',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
