# Generated by Django 5.2.8 on 2026-01-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_selectedgame_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
