# Generated by Django 5.0.4 on 2024-05-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rename_result_shape_tiebreaker_result_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingPointSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='resultconfig',
            name='starting_points',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.startingpointsystem'),
        ),
    ]
