# Generated by Django 5.2.8 on 2026-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_name_alter_game_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
