# Generated by Django 4.2.9 on 2026-01-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_game_max_players_game_min_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='selectable',
            field=models.BooleanField(default=True),
        ),
    ]
