# Generated by Django 4.2.9 on 2026-02-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_selectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedgame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
