# Generated by Django 5.0.6 on 2024-05-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0014_alter_game_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultconfig',
            old_name='scoring_points',
            new_name='has_points',
        ),
        migrations.RemoveField(
            model_name='resultconfig',
            name='is_assymmetric',
        ),
        migrations.RemoveField(
            model_name='resultconfig',
            name='starting_points',
        ),
        migrations.RemoveField(
            model_name='resultconfig',
            name='starting_position',
        ),
        migrations.AddField(
            model_name='resultconfig',
            name='has_starting_player_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resultconfig',
            name='is_asymmetric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultconfig',
            name='starting_points_system',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='game.startingpointsystem'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.platform'),
        ),
    ]
