# Generated by Django 5.0.4 on 2024-06-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_rename_scoring_points_resultconfig_has_points_and_more"),
        ("league", "0003_rename_number_league_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectedgame",
            name="league",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_games",
                to="league.league",
            ),
            preserve_default=False,
        ),
    ]
