# Generated by Django 4.2.9 on 2026-05-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_finalize_tiebreaker_wincondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wincondition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='winconditionoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
