# Generated by Django 4.1.2 on 2023-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('Angekündigt', 'Announced'), ('Anmeldung offen', 'Open'), ('Läuft', 'Running'), ('Beendet', 'Done')], default='Beendet', max_length=15),
        ),
    ]
