# Generated by Django 4.1.2 on 2022-10-23 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('season', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
