# Generated by Django 4.1.2 on 2023-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='number',
            new_name='month',
        ),
        migrations.AlterField(
            model_name='season',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
