# Generated by Django 4.1.2 on 2022-10-31 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('season', '0003_alter_registration_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
