# Generated by Django 4.1.2 on 2023-05-21 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0006_alter_season_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month in the current year'),
        ),
    ]
