# Generated by Django 4.1.2 on 2023-04-09 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=88, unique=True)),
                ('platform', models.CharField(choices=[('BGA', 'BGA'), ('Yucata', 'Yucata')], default='BGA', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='GameSettingsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=88, unique=True)),
                ('is_bool', models.BooleanField()),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameSettingsOptionBool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamesettingscategory')),
            ],
        ),
        migrations.CreateModel(
            name='GameSettingsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=139)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='game.gamesettingscategory')),
            ],
        ),
    ]
