# Generated by Django 4.1.2 on 2022-10-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameoptioncategory',
            old_name='type',
            new_name='is_bool',
        ),
    ]
