# Generated by Django 4.1.2 on 2023-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('BGA', 'Bga'), ('Yucata', 'Yucata')], default='BGA', max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=88, unique=True),
        ),
    ]
