# Generated by Django 4.1.2 on 2023-03-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_platform_alter_game_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesettingscategory',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('BGA', 'BGA'), ('Yucata', 'Yucata')], default='BGA', max_length=6),
        ),
    ]
