# Generated by Django 4.1.2 on 2022-10-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_type_gameoptioncategory_is_bool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameOptionCategory',
            new_name='GameSettingsCategory',
        ),
        migrations.RenameModel(
            old_name='GameOption',
            new_name='GameSettingsOption',
        ),
    ]
