# Generated by Django 4.1.2 on 2023-03-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_category_gamesettingscategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettingscategory',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='game.game'),
        ),
        migrations.CreateModel(
            name='GameSettingsOptionBool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.BooleanField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamesettingscategory')),
            ],
        ),
    ]
