# Generated by Django 4.1.2 on 2023-03-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamesettingscategory_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettingscategory',
            name='name',
            field=models.CharField(max_length=88, unique=True),
        ),
        migrations.AlterField(
            model_name='gamesettingsoption',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='game.gamesettingscategory'),
        ),
    ]
