# Generated by Django 4.2.1 on 2024-01-03 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                          django.core.validators.MaxValueValidator(12)],
                                              verbose_name='month in the current year')),
                ('status', models.CharField(
                    choices=[('Nächste', 'Next'), ('Anmeldung offen', 'Open'), ('Laufend', 'Running'),
                             ('Beendet', 'Done')], default='Nächste', max_length=15)),
            ],
        ),
    ]
