# Generated by Django 5.2 on 2025-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('NEXT', 'Next'), ('OPEN', 'Open'), ('RUNNING', 'Running'), ('DONE', 'Done')], default='NEXT', max_length=15),
        ),
    ]
