# Generated by Django 4.2.9 on 2025-12-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
