# Generated by Django 5.0.4 on 2024-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_initial'),
        ('user', '0002_rename_player_platformplayer_player_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='seasons_participating', to='user.playerprofile'),
        ),
    ]
