# Generated by Django 4.2.9 on 2026-01-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_season_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seasonparticipant',
            index=models.Index(fields=['season', 'profile'], name='season_seas_season__894564_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonparticipant',
            index=models.Index(fields=['season', 'rank'], name='season_seas_season__213791_idx'),
        ),
    ]
