# Generated by Django 5.1.1 on 2024-12-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_alter_season_participants'),
        ('user', '0002_rename_player_platformplayer_player_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='participants',
        ),
        migrations.CreateModel(
            name='SeasonParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_participants', to='user.playerprofile')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='season.season')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('season', 'participant')},
            },
        ),
    ]
