# Generated by Django 5.1.1 on 2024-12-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_remove_season_participants_seasonparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonparticipant',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
