# Generated by Django 4.2.9 on 2026-05-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'Todo'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Declined', 'Declined')], default='To Do', max_length=20),
        ),
    ]
