# Generated by Django 4.1.2 on 2022-10-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bga_name',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
    ]
