[phases.build]
cmds = [
    'pip install -r requirements.txt',
    'python prod_manage.py collectstatic --noinput'
]

[start]
cmd = 'python prod_manage.py migrate && gunicorn django_rest.wsgi:application --bind 0.0.0.0:$PORT'
